### ISSUE TITLE
Some of my users can't join using 3.6, was not happening with 3.5

### ISSUE THREAD

**Issue by matipoirierg** [dejvokep/safe-net#13]
[12:34:47 WARN]: [SafeNET] DENIED (code B9): Failed to authenticate session "morenitojp" (044943b1-8b5c-39be-9e0f-501b449ef432): no properties found.

**Comment by dejvokep** [comment]
Hey 👋

thanks for submitting this issue. I've known this issue already, however, could you please tell if this happens only with offline players?

Thanks.
~ dejvokep

**Comment by dejvokep** [comment]
Fixed by #14. In case of any other questions, do not hesistate and contact me again. :)
